export const CART_ITEM_COUNT = "CART_ITEM_COUNT";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
